version: '3.8'

services:
  gh-ost:
    build:
      context: .
      dockerfile: Dockerfile

    # gh-ost を実行するコマンド
    command: >
      gh-ost
        --allow-on-master
        --host=${MYSQL_CONTAINER}
        --port=3306
        --user=${MYSQL_USER}
        --password=${MYSQL_PASSWORD}
        --database=${MYSQL_DATABASE}
        --table=${MYSQL_TABLE}
        --verbose
        --alter="${GH_OST_ALTER}"
        --switch-to-rbr
        --execute

    environment:
      MYSQL_NETWORK: ${MYSQL_NETWORK}
      MYSQL_CONTAINER: ${MYSQL_CONTAINER}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TABLE: ${MYSQL_TABLE}
      GH_OST_ALTER: ${GH_OST_ALTER}

    networks:
      - default

networks:
  default:
    name: ${MYSQL_NETWORK}
    external: true
